### ISSUE TITLE
Set FIDO PIN

### ISSUE THREAD

**Issue by mb720** [solokeys/solo2-cli#114]
Hi and thanks a lot for Solo!

Is it possible to set a FIDO PIN for a Solo 2 key using `solo2` 0.2.2 on Arch Linux?

I'm looking for the equivalent of `solo key set-pin` in [solo1-cli](https://github.com/solokeys/solo1-cli).

Issues like [this one](https://github.com/solokeys/solo2-cli/issues/109) recommend setting a PIN to make the key work in certain scenarios.

**Comment by mb720** [comment]
Thanks @schdro, this worked:

  * `pacman -S libfido2` to install `fido2-token`
  * List devices to get name: `fido2-token -L`
  * Set PIN: `fido2-token -S /dev/hidraw2`

**Comment by 0spinboson** [comment]
I've tried to do the same thing with my solo2 device running the aug 2022 fw, but when I try to set the pin usign fido2-token -S I get "FIDO_ERR_NOT_ALLOWED".
