### ISSUE TITLE
Solo2 key not recognized under Ubuntu/Debian

### ISSUE THREAD

**Issue by robpower** [solokeys/solo2-cli#24]
Hello everybody,
Thanks for making this project reality!

That said, I cannot get my solo2 key to be detected by solo2-cli.
(Also the key works to register and authenticate on website by "squeezing", yet the LED never blinks to indicate confirmation is required.)

I tried both on Ubuntu 20.04.3 and Debian 11.
### Steps to reproduce:

1. Get a fresh Debian 11 install
2. Either:
  - Download the binary from release 0.1.0 OR
  - Install through cargo
    - Install cargo (`curl https://sh.rustup.rs -sSf | sh`)
    - Install dependencies (`sudo apt-get install libudev-dev libpcsclist-dev`) **NB:** they should be added to the readme
    - Install solo2-cli (`cargo install solo2`)
3. Install PCSC daemon (`sudo apt-get install pcscd`)
4. Copy 70-solo2.rules under `etc/udev/rules.d` and reboot or reload rules (`sudo udevadm control --reload-rules && sudo udevadm trigger`)
5. Ensure PCSC daemon is running (`sudo service start pcscd && sudo service pcscd status`)
6. Connect Solo2 key and check `dmesg`
```
[ 2782.699240] usb 2-2: new full-speed USB device number 6 using ohci-pci
[ 2783.228068] usb 2-2: New USB device found, idVendor=1209, idProduct=beee, bcdDevice= 1.00
[ 2783.228076] usb 2-2: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[ 2783.228081] usb 2-2: Product: Solo 2 Security Key
[ 2783.228084] usb 2-2: Manufacturer: SoloKeys
[ 2783.228087] usb 2-2: SerialNumber: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
[ 2783.255162] hid-generic 0003:1209:BEEE.0005: hiddev0,hidraw1: USB HID v1.11 Device [SoloKeys Solo 2 Security Key] on usb-0000:00:06.0-2/input1
[ 2783.255413] cdc_acm 2-2:1.2: ttyACM0: USB ACM device
```
7. Run (as root or current user)
```bash
$ solo2 ls


$ solo2 app admin uuid
Error: Empty list of smartcards
```

Any suggestions?
Thanks in advance for your help.

**Comment by joelhaasnoot** [comment]
Similar story on Mac. Just got my Solo2 key

**Comment by robpower** [comment]
Answering myself, from readme file:
> Solo 2 is supported by Ludovic Rousseau's [CCID](https://ccid.apdu.fr/ccid/shouldwork.html#0x12090xBEEE) driver, but there has not been a release. The included [Info.plist](https://github.com/solokeys/solo2-cli/blob/main/Info.plist) works.

On Debian 11 you will need to install a version of libccid >= 1.4.35.

**Comment by felix-gohla** [comment]
> Similar story on Mac. Just got my Solo2 key

Hi! For macOS, have a look at this discussion thread: < https://github.com/solokeys/solo2-cli/discussions/19#discussioncomment-1742575>. We got it working both for Intel and ARM Mac. 😊

**Comment by nickray** [comment]
Yeah this will be fixed (for macOS and "conservative" Linux) with the next release which has basic CTAP support.

**Comment by My1** [comment]
> Yeah this will be fixed (for macOS and "conservative" Linux) with the next release which has basic CTAP support.

wait if solo doesnt have basic ctap support what does it use now?

**Comment by nickray** [comment]
For the purposes of this issue, version v0.1.1 has the basic CTAP support now. Note that not all apps (e.g. NDEF + OATH) are available over CTAP. If your distribution has access to CCID 1.4.35, this will be a better experience.
