### ISSUE TITLE
Update crates.io package

### ISSUE THREAD

**Issue by KizzyCode** [solokeys/solo2-cli#31]
Bump the crates.io package version to `0.1.1`.

Reason:
I'm aware that you can install packages via git (`cargo install --git https://github.com/solokeys/solo2-cli`), however this has the disadvantage that those packages are not tracked via `cargo-update` etc., so it's pretty easy to end up with an outdated/broken version without noticing it.

**Comment by nickray** [comment]
Done, thanks for the reminder.
