### ISSUE TITLE
Cannot use some app commands

### ISSUE THREAD

**Issue by gcochard** [solokeys/solo2-cli#32]
I'm attempting to use the `solo2 app ndef data` and `solo2 app oath list` commands, and I get an explicit panic. When I added some debug statements, it appears that the cli is attempting to send vendor code `0xA4` for `ndef data` and `0xA1` for `oath list`, both of which are outside the expected range for vendor codes.

I checked the [CTAP spec](https://fidoalliance.org/specs/fido-v2.0-id-20180227/fido-client-to-authenticator-protocol-v2.0-id-20180227.pdf) and it says that the range is actually 0x40 to 0xBF, so I expanded the expected range on the solo cli source to match that. When I attempt to run those commands it now hangs after sending the packet over CTAP.

I found those hex values in the apps' sources, so I would expect this to work unless there is another check earlier on in the firmware that is dropping instructions beyond the vendor code range.

Are these commands expected to work on the latest released firmware and CLI?

I can provide detailed trace level logs and backtraces if requested.

**Comment by mskarbek** [comment]
Same here.

**Comment by nickray** [comment]
NDEF and OATH don't work via CTAP, you need CCID for that. Plan to add better errors for this, CTAP support is only currently useful for firmware update (in particular admin app), to unlock firmware improvements on platforms without CCID (mac and older linux distros).

**Comment by mskarbek** [comment]
Ok, rebuilding and installing ccid 1.4.36 helped. I had 1.4.33 originally.

**Comment by nickray** [comment]
Correct, [we're in the CCID driver since version 1.4.35](https://github.com/LudovicRousseau/CCID/releases/tag/1.4.35).
