### ISSUE TITLE
Solokey v2 not working in Windows

### ISSUE THREAD

**Issue by provi1** [solokeys/solo2-cli#35]
Solokey v2 normal version1:20200101.8 and 1:20200101.7 is not working in Windows 10.
if plugged in windows will recordnize the solokey and install the device.

when trying to register the key to a web site, i used a test website with different web browser. windows show form to touch key right now.
and solokey led change light a little bit. but nothing happens if i touch the device.

with ios and nfc using it on the test website it is working like expected.

with solokey v2 hacker version 1:20200101.8 if plugged in windows will recordnize the solokey and install the device.
when trying to register the key to a web site, i used a test website with different web browser. windows show form to touch key right now.
and solokey led change light to another color. if i touch the device now solokey registration on that test website is successfull.
i can use it same way to loggin to the test website.

**Comment by GoetzGoerisch** [comment]
I second this for MS accounts.

Was able to register and use with GitHub and GMail on Windows, though.

**Comment by provi1** [comment]
Hi Götz,
what Windows version have u used?
and did you use the normal Solokey v2 or the hacker version?


thx
Alex

**Comment by GoetzGoerisch** [comment]
Windows 10 19044.1503 - 21H2
normal version
personal MS account

**Comment by conorpp** [comment]
Could you try updating to newly released 1:20200101.9 and try again?  Just fixed a windows issue where it would occasionally report "Unable to use this key".

**Comment by GoetzGoerisch** [comment]
@conorpp this solo2 is already running `firmware 1:20200101.9`

**Comment by provi1** [comment]
@conorpp my normal solo2 key is on firmware 1:20200101.9
and the issue still appear. 
i have tried in windows 10 21h2 home and windows 10 21h2 professional.
with updated edge and firefox browser.

i have done updating the solokey with cmd as normal user and with admin privileg.
both update process worked. 
with normal user only PSCS is available, with admin privileg CTAP+PCSC is available.


are there any options to deliver logs with more details or do you have a test tool to test the key in windows without a browser, with more log details?

**Comment by daFritz84** [comment]
I also tried my solo2 within Windows 10 21H2 Professional with firmware is 1:20200101.9.
I couldn't get neither my MS account (Opera Browser) nor Windows 10 Hello working.

**Comment by mabramux** [comment]
> Hi, issue still in Solokey v2 normal version1:20200101.9 , i have just tested it.
> 
> thx

The problem described above still seems to exist. Same here. I tried with version 1:20200101.9 on Windows 20H2. I also tried with Edge and Firefox on webauthn.io. Unfortunately no success.

There seems to be no problems with Linux. With my Arch Linux and Firefox or Chromium everything works fine. I can register my solo v2 and login on webauthn.io

**Comment by pbl987** [comment]
i have version1:20200101.9 too.

when do we get a new version? i can't use the key.

**Comment by lwaegele** [comment]
I just received two Solokey v2 (normal) and have the same issues with Windows 11 Home (21H2). 
Firmware version is 1:20200101.9. 

I cannot register them as a security key for Windows Hello and it is also not working with Firefox with the same symptoms as described above. 

Running `list` (with solo2 0.1.1) displays "PCSC only" for the keys.
Trying to run `fido init` results in "Error: CTAP unavailable".

Any help/hints appreciated.

**Comment by daFritz84** [comment]
@lwaegele There was some information regarding this issue in the last kickstarter news (19th April):

> The Windows issue has been solved.  Turns out our FIDO credential was excessively long, resulting in broken operations with some sites that were more restrictive in this specification.  We have a firmware upgrade that is nearing release...a few more bugs to iron out and then it will be made available for general use.

**Comment by nickray** [comment]
This is not a CLI issue.

**Comment by daFritz84** [comment]
@nickray I understand that this is not a cli issue

But since we are not allowed to post issues to the firmware repo yet, how are we supposed to report and track firmware related issue?

**Comment by provi1** [comment]
Hi,
i also understand that, but please provide another way to open this issue at the correct place.
via email i got the information, in january to open an issue an github.

sorry but this leaves me really unhappy.
