### ISSUE TITLE
New key, cannot list or update

### ISSUE THREAD

**Issue by bendem** [solokeys/solo2-cli#55]
Just received my solo2, thought I'd check if there was an update before using it. Can't seem to even get it recognized by the `solo2` program.

```
➜  ~ solo2 update          
Downloading latest release from https://github.com/solokeys/solo2/
Fetched firmware version 1:20200101.9
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: The operation requires a Smart Card, but no Smart Card is currently in the device', /home/bendem/.cargo/registry/src/github.com-1ecc6299db9ec823/solo2-0.1.1/src/device/pcsc.rs:98:50
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Environment information:

```
➜  ~ cat /etc/fedora-release
Fedora release 34 (Thirty Four)
➜  ~ rustc --version             
rustc 1.59.0 (9d1b2106e 2022-02-23)
➜  ~ dnf list --installed pcsc-lite systemd
Installed Packages
pcsc-lite.x86_64                     1.9.1-1.fc34                      @anaconda
systemd.x86_64                       248.10-1.fc34                     @updates
➜  ~ cat /etc/udev/rules.d/70-solo2.rules 
# NXP LPC55 ROM bootloader (unmodified)
SUBSYSTEM=="hidraw", ATTRS{idVendor}=="1fc9", ATTRS{idProduct}=="0021", TAG+="uaccess"
# NXP LPC55 ROM bootloader (with Solo 2 VID:PID)
SUBSYSTEM=="hidraw", ATTRS{idVendor}=="1209", ATTRS{idProduct}=="b000", TAG+="uaccess"
# Solo 2
SUBSYSTEM=="tty", ATTRS{idVendor}=="1209", ATTRS{idProduct}=="beee", TAG+="uaccess"
# Solo 2
SUBSYSTEM=="usb", ATTRS{idVendor}=="1209", ATTRS{idProduct}=="beee", TAG+="uaccess"
```

**Comment by nickray** [comment]
I'd wait on the update, working on fixing a few issues for good.

This specific issue I haven't seen before. Does `solo2 ls` fail in the same way?

**Comment by bendem** [comment]
Yup, same error on solo ls.

5 Mar 2022 18:49:50 Nicolas Stalder ***@***.***>:

**Comment by nickray** [comment]
Looking at https://src.fedoraproject.org/rpms/pcsc-lite/blob/rawhide/f/pcsc-lite.spec, it seems `pcsc-lite-ccid` is recommended but not enforced. Do you have it installed?

**Comment by bendem** [comment]
```
Package pcsc-lite-ccid-1.4.34-1.fc34.x86_64 is already installed.
```

**Comment by bendem** [comment]
On windows I'm getting 
```
PS C:\Users\bendem> .\Downloads\solo2-v0.1.1-x86_64-pc-windows-msvc.exe ls
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: The smart card has been removed, so further communication is not possible', src\device\pcsc.rs:98:50
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by pbl987** [comment]
> I have/had the same problem due to an integrated smart card reader device. `pcsc_scan` lists another reader device at first; solo2 is only second. As a result I get two different error messages by using `solo2 list` command.

Thats the cause! I have a Reiner SCT cardreader installed. As soon as i deactivated it in the device manager, _solo2-v0.1.1-x86_64-pc-windows-msvc.exe_ started to begin working. It could then print out the version number, it is _20200101.9_.

By the way, the update command download and overwrites the firmware with the same version.
And it doens't work on any site i tested, same as in the other issues.

**Comment by pbl987** [comment]
this issue is closed but there is no new version???
i really would like start using my key, it has been 3 weeks now...

**Comment by bendem** [comment]
> this issue is closed but there is no new version???
> i really would like start using my key, it has been 3 weeks now...

There is a new version though. Fix is in https://github.com/solokeys/solo2-cli/releases/tag/v0.2.0: 

> fix for multiple smartcard readers (@borgoat)

I have not tested it yet. You can try inserting a smart card in the other reader to see if that fixes it for you.
