### ISSUE TITLE
Duo HOTP key rejected

### ISSUE THREAD

**Issue by loveshack** [solokeys/solo2-cli#59]
I tried to add a HOTP key (for Duo), but it was rejected with `Error: invalid length at 48`.  The secret is 51 characters base32.  (From the --help example I assume it should be given as base32, and it would be good if the help said.)  It works with oathtool, for instance.

**Comment by westerguard** [comment]
I have the same problem with my Amazon TOTP code containing 52 characters base32.

**Comment by nickray** [comment]
I believe this is fixed with the release of https://github.com/solokeys/solo2-cli/releases/tag/v0.2.0.

**Comment by westerguard** [comment]
Well, I still get the same output with cli version 0.2.0.

**Comment by loveshack** [comment]
> Well, I still get the same output with cli version 0.2.0.

Likewise.
