### ISSUE TITLE
Solo V2 not working with all websites

### ISSUE THREAD

**Issue by screendriver** [solokeys/solo2-cli#61]
I just received my SoloKey V2 and tried to register it everywhere where I already use my SoloKey V1. Unfortunately some platforms seem to have problems with the V2 (Firmware 20200101.9). For example Amazon AWS or GitLab does not recognize the key. With the V1 everything is working as expected.

Is this an already known issue?

**Comment by nickray** [comment]
This is not a CLI issue.

**Comment by nickray** [comment]
It has discussions, and there's also https://github.com/solokeys/fido-authenticator/issues
