### ISSUE TITLE
48 character TOPT "To long"

### ISSUE THREAD

**Issue by Filyx20** [solokeys/solo2-cli#66]
on websites that for example could be amazon, the totp secret is 52 characters long. however when registering them in solo2-cli it states thew folowing: 
`solo2 app oath -a register Amazon "52 character long TOPT code"`
`Error: invalid length at 48.`

**Comment by nickray** [comment]
My AWS root TOTP is 64 characters long and things work. PR https://github.com/solokeys/solo2-cli/pull/41 isn't published though, is your use case fixed after `cargo install --git https://github.com/solokeys/solo2-cli --locked`?

**Comment by mkopec** [comment]
I am seeing the same issue with a 52-character TOTP secret from Amazon, on `solo2-cli` rev `5fd8e5a8` and solo2 firmware `2:20220822.0`
