### ISSUE TITLE
fail to compile from repo 

### ISSUE THREAD

**Issue by Miyamoto72** [solokeys/solo2-cli#72]
Tried to compile solo2 from the repo in order to get rid of the need to have a smartcard in my reader (which is built into ma laptop). But build fails.

Here's what I did:

```
git clone https://github.com/solokeys/solo2-cli.git solo2
cd solo2/
cargo build
```
Build runs fine for quite a while, but finally fails with this error message:

```    [...]
   Compiling solo2 v0.1.2 (/home/user/temp/solo2)
   Compiling serde_yaml v0.8.23
   Compiling serde-big-array v0.3.2
   Compiling toml v0.5.8
   Compiling ureq v2.4.0
error: there is no argument named `uuid`
   --> src/bin/solo2/main.rs:336:61
    |
336 |                     let url = format!("https://s2pki.net/s2/{uuid}/x255.txt");
    |                                                             ^^^^^^

error: could not compile `solo2` due to previous error
```
LinuxMint 20.3 (underlying Ubuntu 20.04) running here, rustc 1.57.0+dfsg1+llvm-0ubuntu1~20.04.1, cargo 0.58.0-0ubuntu1~20.04.1, gcc 9.3.0

I'd be happy to provide more info, pls feel free to ask.

**Comment by nickray** [comment]
You need to update to Rust 1.58 for the "format strings": https://blog.rust-lang.org/2022/01/13/Rust-1.58.0.html#captured-identifiers-in-format-strings.

I'll bump the `rust-version` entry in `Cargo.toml`.
