### ISSUE TITLE
Solo v2 enters into a constant "getting ready" "touch device" loop on Windows 11

### ISSUE THREAD

**Issue by ssg** [solokeys/solo2-cli#89]
This is not a CLI problem but, we can't file bugs in the firmware repository, and the previous bug (#35) was closed because "it wasn't CLI related". If you don't want us to report firmware bugs, explicitly say so.

Firmware version: 2:20220822.0 (2.964.0)

I'm trying to add SoloKey as a FIDO2 device to a web site using Microsoft Edge (Chromium) on Windows 11. The Windows Hello prompt constantly switches between "Getting ready" and "Touch device" states. If I can catch it during "touch device" it works fine, but it's an accessibility nightmare.

This doesn't happen with YubiKeys.

`solo2 app fido init` and `sudo2 app fido wink` commands also give `Error: CTAP Unavailable` error.

**Comment by papezg** [comment]
I have same problem, 
Windows version:
![image](https://github.com/solokeys/solo2-cli/assets/10542421/eb163148-64da-43f3-b9a0-8f766ab5d778)

No drivers available anymore
![image](https://github.com/solokeys/solo2-cli/assets/10542421/a17b8192-f9cb-466f-b394-8109ace18957)
When i try to update driver there is nothing. I was searching for suitable driver but no luck.

**Comment by hkuhn42** [comment]
I had the same issue after I set a PIN. After i reset the Stick in windows settings (via hello / login settings) and NOT setting a PIN, it works for me again.

**Comment by JohnLGalt** [comment]
@ssg Is this actually fixed? Just curious....

**Comment by ssg** [comment]
@JohnLGalt It hasn't happened to me for a long time. Perhaps it was a problem with Windows? I'm not sure. Never heard from SoloKeys team that it's been fixed or addressed though.

**Comment by JohnLGalt** [comment]
Thanks for the response, and good to know 👍

**Comment by MistakingManx** [comment]
It's happening on my Windows 10 machine, so I guess it's a windows thing?
